config/urls.py
from django.contrib import admin
from django.urls import path,include
from todo.views import todolist
urlpatterns = [
    path("",todolist,name="todolist"),
    path('admin/', admin.site.urls),
    path("todo/",include("todo.urls",namespace="todo")),
]

todo/urls.py
from django.urls import path
from .views import todolist,todoitem,delete_todo_list,todolist_update , delete_todo_item  #,todoitem_update

app_name="todo"

urlpatterns = [
    path("",todolist,name="todolist"),
    path("<int:id>/",todoitem,name="todoitem"),
    path("delete/<int:id>/",delete_todo_list,name="delete_todo_list"),
    path("delete/<slug:slug>/",delete_todo_item,name="delete_todo_item"),
    path("update/<int:id>/",todolist_update,name="todolist_update"),
    #path("edit/<int:todolist__id>/",todoitem_update,name="todoitem_update"),
    
]

todo/models.py
from django.db import models
from django.urls import reverse



class ToDoList(models.Model):
    title=models.CharField(max_length=100)
    update=models.DateTimeField(auto_now=True)
    slug=models.SlugField(unique=True)
    
    def __str__(self):
        return self.title
    
    # def get_absolute_url(self):
    #     return reverse("model_detail", kwargs={"pk": self.pk})
    

class ToDoItem(models.Model):
    todolist=models.ForeignKey(ToDoList,related_name="todolist",on_delete=models.CASCADE)
    title=models.CharField(max_length=100)
    content=models.TextField()
    update=models.DateTimeField(auto_now=True)
    time_todo=models.DateTimeField()
    slug=models.SlugField(unique=True)
    
    def __str__(self):
        return f"{self.title}"

todo/forms.py
from django import forms

from .models import ToDoItem,ToDoList

class TodolistForm(forms.ModelForm):
    class Meta:
        model=ToDoList
        fields=['title','slug']

class TodoitemForm(forms.ModelForm):
    class Meta:
        model=ToDoItem
        fields=['title','content','time_todo','slug']
    

todo/views.py
from django.shortcuts import render,redirect
from .models import ToDoList,ToDoItem
from .forms import TodolistForm,TodoitemForm
from django.http import HttpResponse

# show all to do list

def todolist(request):
    todolist=ToDoList.objects.all()
    form=TodolistForm()
    if request.method=="POST":
        form=TodolistForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todo:todolist')
    else:
        return render(request,"todo/todolist.html",{"mylist":todolist,"form":form})

# show  one specific todo list and its items

def todoitem(request,id=None):
    list=ToDoList.objects.get(id=id)
    item=ToDoItem.objects.all().filter(todolist_id=list)
    # number=len(item)
    form=TodoitemForm()
    if request.method=="POST":
        form=TodoitemForm(request.POST)
        if form.is_valid():
            todolist=form.todolist_id=list
            form2=ToDoItem(todolist=todolist,time_todo=form.cleaned_data['time_todo'],title=form.cleaned_data['title'],content=form.cleaned_data['content'],slug=form.cleaned_data['slug'])
            form2.save()
            return redirect('todo:todoitem',id=list.id)
        return HttpResponse("your item of form is invalid")
    return render(request,"todo/todolist_item.html",{"item":item,"form":form})


# update the todo list
def todolist_update(request,id=None):
    todolist=ToDoList.objects.get(id=id)
    form=TodolistForm()
    if request.method=="POST":
        form=TodolistForm(request.POST)
        if form.is_valid():
            todolist.delete()
            title=form.cleaned_data['title']
            slug=form.cleaned_data['slug']
            todolist.title=title
            todolist.slug=slug
            todolist.save()
            return redirect('todo:todolist')
    else:
        return render(request,"todo/todolist_update.html",{"mylist":todolist,"form":form})




# def todoitem_update(request,todolist__id):
#     list1=ToDoItem.objects.get(id=todolist__id)
#     form=TodoitemForm()
#     if request.method=="POST":
#         form=TodoitemForm(request.POST)
#         if form.is_valid():
#             todolist=list1.todolist
#             list1.delete()
#             title=form.cleaned_data['title']
#             content=form.cleaned_data['content']
#             time_todo=form.cleaned_data['time_todo']
#             slug=form.cleaned_data['slug']
            
#             newlist=ToDoItem(todolist=todolist,title=title,content=content,time_todo=time_todo,slug=slug)
#             newlist.save()
#             return redirect('todo:todoitem',id=newlist.id)
#     return render(request,"todo/todolist_item_update.html",{"item":list1,"form":form})
    



def delete_todo_list(request,id):
    list=ToDoList.objects.get(id=id)
    list.delete()
    return redirect("todo:todolist")

def delete_todo_item(request,slug):
    list=ToDoItem.objects.get(slug=slug)
    list.delete()
    return redirect("todo:todoitem",id=list.todolist.id)



# 

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'todo:todolist' %}">home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div> -->
        </div>
      </nav>
    {% block title %}
      
    {% endblock title %}

    {% block content %}
      
    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>
<style>
    body{
        background-color: cadetblue;
    }
</style>

</html>

templates/todo/todolist.html
{% extends "base.html" %}

{% block content %}


<div class="container" style="margin-top:100px;">
    <table class="table table-primary">
        <thead>
            
          <tr>
            <th scope="col">title</th>
            <th scope="col">number</th>
            <th scope="col">update</th>
            <th scope="col">delete</th>
          </tr>
        </thead>
        <tbody>
            {% for list in mylist %}
            <tr>
                <td><a href="{% url 'todo:todoitem' list.id %}" class="btn btn-success">{{list.title}}</a></td>
                <td> </td>
                <td><a href="{% url 'todo:todolist_update' list.id %}" class="btn btn-primary">update</a></td>
                <td><a href="{% url 'todo:delete_todo_list' list.id %}" class="btn btn-danger">delete</a></td>
              </tr>
              
            {% endfor %}
          
           
        </tbody>
    </table>
</div>

    <div class="container mt-5 mb-5" id="div" style="padding-left: 200px;">
        <p style="color: green;padding-top:20px">ADD YOUR TODOLIST</p>
      <form action="" method="POST" >
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label>title</label>
            <input type="text" class="form-control" name="title" id="inputEmail4" placeholder="title"  required >
          </div>
          <div class="form-group col-md-6">
            <label for="inputSlug">slug</label>
            <input type="slug" name="slug" class="form-control" id="inputPassword4" placeholder="slug" required >
          </div>
        <button type="submit" class="btn btn-primary mt-3 mb-5">post</button>
        </div>
      </form>
    </div>



<style>
    .table{
        margin: auto;
        width: 800px;
    }
    td{
        align-items: center;
    }

    #div{
        width: 600px;
        margin-bottom: 50px;
        margin: auto;
        padding: auto;
        background-color: chocolate;
    }
    a{
        text-decoration: none;
    }
    
</style>
{% endblock content %}

templates/todo/todolist_item.html
{% extends "base.html" %}



{% block content %}


<div class="container" style="margin-top:100px;">
    <table class="table table-primary">
        <thead>
            
          <tr style="border: solid 5px blue;">
            <th scope="col">title</th>
            <th scope="col">content</th>
            <!-- <th scope="col">update</th> -->
            <th scope="col">delete</th>
          </tr>
        </thead>
        <tbody>
            {% for item in item %}
            <tr style="border: solid 5px blue;">
                <td style="padding-top: 80px;"><h3>{{item.title}}</h3></td>
                <td> <div style="height: 200px;width: 300px;overflow-y:scroll;border: solid ;" > {{item.content}}</div></td>
                <!-- <td style="padding-top: 80px;"><a href="" class="btn btn-primary">edit</a></td> -->
                <td style="padding-top: 80px;"><a href="{% url 'todo:delete_todo_item' item.slug  %}" class="btn btn-danger">delete</a></td>
            </tr>
              
            {% endfor %}
          
           
        </tbody>
    </table>
</div>

    <div class="container mt-5 mb-5" id="div" style="padding-left: 100px;">
        <p style="color: green;padding-top:20px">ADD YOUR TODOITEM</p>
      <form action="" method="POST" >
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label>title</label>
            <input type="text" class="form-control" name="title" id="" placeholder="title" required >
          </div>
          <div class="form-group col-md-6">
            <label>content</label>
            <textarea type="text" style="width: 250px;height:300px" class="form-control" name="content" id="" placeholder="content" required></textarea>
          </div>
          <div class="form-group col-md-6">
            <label>time</label>
          
            <input type="datetime-local" datetime="YYYY-MM-DDThh:mm:ssTZD"  class="form-control" name="time_todo" required >
          </div>
          <!-- <div class="form-group col-md-6">
            <label>todolist</label>
          
            <input type="text" datetime="YYYY-MM-DDThh:mm:ssTZD"  class="form-control" name="todolist" >
          </div> -->
          <div class="form-group col-md-6">
            <label>slug</label>
            
            <input type="slug"  class="form-control" name="slug" placeholder="slug" required >
          </div>
        <button type="submit" class="btn btn-primary mt-3 mb-5">post</button>
        </div>
        
      </form>
      
    </div>



<style>
    .table{
        margin: auto;
        width: 800px;
    }
    td{
        align-items: center;
    }

    #div{
        width: 600px;
        margin-bottom: 50px;
        margin: auto;
        padding: auto;
        background-color: chocolate;
    }
    a{
        text-decoration: none;
    }
    #td5{
        width: 300px;
        height: 200px;
        overflow-y: scroll;
    }
    
</style>

{% endblock content %}

templates/todo/todolist_item_update.html
{% extends "base.html" %}



{% block content %}


<div class="container" style="margin-top:100px;">
    <table class="table table-primary">
        <thead>
            
          <tr style="border: solid 5px blue;">
            <th scope="col">title</th>
            <th scope="col">content</th>
            <!-- <th scope="col">update</th> -->
            <!-- <th scope="col">delete</th> -->
          </tr>
        </thead>
        <tbody>
            <tr style="border: solid 5px blue;">
                <td style="padding-top: 80px;"><h3>{{item.title}}</h3></td>
                <td> <div style="height: 200px;width: 300px;overflow-y:scroll;border: solid ;" > {{item.content}}</div></td>
            </tr>
              
           
          
           
        </tbody>
    </table>
</div>

    <div class="container mt-5 mb-5" id="div" style="padding-left: 100px;">
        <p style="color: green;padding-top:20px">ADD YOUR TODOITEM</p>
      <form action="" method="POST" >
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label>title</label>
            <input type="text" class="form-control" name="title" id="" placeholder="title" required >
          </div>
          <div class="form-group col-md-6">
            <label>content</label>
            <textarea type="text" style="width: 250px;height:300px" class="form-control" name="content" id="" placeholder="content" required></textarea>
          </div>
          <div class="form-group col-md-6">
            <label>time</label>
          
            <input type="datetime-local" datetime="YYYY-MM-DDThh:mm:ssTZD"  class="form-control" name="time_todo" required >
          </div>
          <!-- <div class="form-group col-md-6">
            <label>todolist</label>
          
            <input type="text" datetime="YYYY-MM-DDThh:mm:ssTZD"  class="form-control" name="todolist" >
          </div> -->
          <div class="form-group col-md-6">
            <label>slug</label>
            
            <input type="slug"  class="form-control" name="slug" placeholder="slug" required >
          </div>
        <button type="submit" class="btn btn-primary mt-3 mb-5">post</button>
        </div>
        
      </form>
      
    </div>



<style>
    .table{
        margin: auto;
        width: 800px;
    }
    td{
        align-items: center;
    }

    #div{
        width: 600px;
        margin-bottom: 50px;
        margin: auto;
        padding: auto;
        background-color: chocolate;
    }
    a{
        text-decoration: none;
    }
    #td5{
        width: 300px;
        height: 200px;
        overflow-y: scroll;
    }
    
</style>

{% endblock content %}

templates/todo/todolist_update.html
{% extends "base.html" %}

{% block content %}


<div class="container" style="margin-top:100px;">
    <table class="table table-primary">
        <thead>
            
          <tr>
            <th scope="col">title</th>
            <th scope="col">slug</th>
            {% comment %} <th scope="col">update</th> {% endcomment %}
            <th scope="col">delete</th>
          </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{mylist.title}}</td>
                <td>  {{mylist.slug}}</td>
                <td><a href="{% url 'todo:delete_todo_list' mylist.id %}" class="btn btn-danger">delete</a></td>
              </tr>

          
           
        </tbody>
    </table>
</div>
<!--  -->
    <div class="container mt-5 mb-5" id="div" style="padding-left: 200px;">
        <p style="color: green;">ADD YOUR TODOLIST</p>
      <form action="" method="POST" >
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label>title</label>
            <input type="text" class="form-control" name="title" id="inputEmail4" placeholder="title" required>
          </div>
          <div class="form-group col-md-6">
            <label for="inputSlug">slug</label>
            <input type="slug" name="slug" class="form-control" id="inputPassword4" placeholder="slug" required >
          </div>
        <button type="submit" class="btn btn-primary mt-3 mb-5">post</button>
        </div>
      </form>
    </div>



<style>
    .table{
        margin: auto;
        width: 800px;
    }
    td{
        align-items: center;
    }

    #div{
        width: 600px;
        margin-bottom: 50px;
        margin: auto;
        padding: auto;
        background-color: chocolate;
    }
    a{
        text-decoration: none;
    }
    
</style>
{% endblock content %}